### ISSUE TITLE
How to install multiple packages

### ISSUE THREAD

**Issue by dermeister0** [gep13/chocolatey-azuredevops#49]
## Expected Behavior

Multiple packages are installed.

## Current Behavior

Chocolatey can't find "name1 name2" package.

## Possible Solution

Support package names separator or update description to not allow multiple packages to be installed.

## Steps to Reproduce (for bugs)

```
- task: ChocolateyCommand@0
  inputs:
    command: 'install'
    installPackageId: 'nuget.commandline'
```

## Your Environment

* Module version used: 0.2.0
* Operating System and PowerShell version: Azure DevOps
